### ISSUE TITLE
Not working on windows

### ISSUE THREAD

**Issue by itaditya** [colshacol/remmy#4]
I first tried my own config but didn't work then I tried to use the sample present in the repo. It creates a folder like adi if I try `remmy comp adi`. Then it stops with error - 
![image](https://user-images.githubusercontent.com/15871340/39671872-0f74ba16-513e-11e8-9c72-d9a3ff511315.png)

**Comment by colshacol** [comment]
Thanks for the report!

Could you show me your `./remmy.json`?

**Comment by itaditya** [comment]
I ran the the one provided in this repo

**Comment by itaditya** [comment]
@colshacol I meant that I used this one https://github.com/colshacol/remmy/blob/master/remmy.json
