### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by itaditya** [colshacol/remmy#5]
@colshacol I have so much use for remmy but sadly I'm not able to use it on either Ubuntu or Windows. I had already opened an issue for Windows #4 . Today I tried remmy on Ubuntu and got this error.

![capture](https://user-images.githubusercontent.com/15871340/40772414-8a6443f6-64dd-11e8-96da-a26368f6b4a6.PNG)

To test remmy I used exactly the same `remmy.json` and `sample/` as present [here](https://github.com/colshacol/remmy)  please look into it. I'd be glad to provide all the support I can. 

System Details - 
Node v10.3
Ubuntu 16.04

**Comment by colshacol** [comment]
My apologies, friend. I've been busy at work!

Here's the deal with remmy.

I created it a while back, and then I wanted to get crazy with it and make some cool upgrades. So I started working on that, deleted v1 altogether, and then didn't finish it.

So, yeah, it doesn't work on any computer, haha.

But, if you'd use it, I'll finish it for you. :+1:

**Comment by colshacol** [comment]
Oh, hey, it turns out I didn't delete the original source! But I won't be maintaining it, haha.

I'll work to get v2 published very soon. :+1:

**Comment by itaditya** [comment]
Thanks @colshacol , thanks for taking this on. I thought this was a cool project and so I rolled my own solution https://github.com/itaditya/birla

**Comment by colshacol** [comment]
Let's see who can create a more bad-ass, featureful implementation!

**Comment by itaditya** [comment]
Love your enthusiasm, bring on the challenge

**Comment by colshacol** [comment]
@itaditya So I am sitting on v2 only lacking docs at the moment, good sir. I think you'll be delighted!

**Comment by colshacol** [comment]
![remmy-demo](https://user-images.githubusercontent.com/19484365/41815765-cd59d590-7739-11e8-9600-f1c0705772aa.gif)

**Comment by itaditya** [comment]
@colshacol this looks amazing. I'll take it for a drive today. Very excited about this

**Comment by colshacol** [comment]
@itaditya Sorry, friend. I haven't published it yet, I do not think! I have to get docs going for v2 and I'll let you know when it goes live. :)

**Comment by itaditya** [comment]
Ok :)

**Comment by colshacol** [comment]
Dang, I have had 0 time to work on documenting this freaking thing. -_-

I went ahead and put up a basic guide in the README and published v2.

Idk how it is going to act on Windows. 😆 

https://www.npmjs.com/package/remmy
